CREATE TABLE USERS 
    (userName VARCHAR(200) UNIQUE, 
    firstName VARCHAR(200) NOT NULL,
    lastName VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE , 
    password VARCHAR(200), 
    role VARCHAR(200) DEFAULT 0)