
POST http://localhost:5491/project/create
Content-Type: application/json

{
    "projectName":"abc",
    "description":"new",
    "deadline": "1/8/2022",
    "userName": "dan"
}

###
GET http://localhost:5491/project/allprojects
Content-Type: application/json

###
POST http://localhost:5491/user/create
Content-Type: application/json

{
    "userName":"abc",
    "firstName":"new",
    "lastName": "1/8/2022",
    "email": "dan@gmail.com",
    "password": "abc"
}

###
GET http://localhost:5491/user/idle
Content-Type: application/json

###
POST http://localhost:5491/user/login
Content-Type: application/json

{
    "email":"abcd@gmail.com",
    "password": "12345678"
}


###
GET http://localhost:5491/user/check
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkRhbnRleiIsImZpcnN0TmFtZSI6IkRhbmllbCIsImxhc3ROYW1lIjoiS2l0aGVrYSIsImVtYWlsIjoia2FraW55aWRrQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MjAxMzM4MywiZXhwIjoxNjYyMDEzNjgzfQ.LDdt-Rtdt8F80wWpGMCmphOJ7xE-l5T1M9d4RLv23cA

###
GET http://localhost:5491/user/assigned
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImtpdGhla2EiLCJmaXJzdE5hbWUiOiJkYW5pZWwiLCJsYXN0TmFtZSI6ImtpdGhla2EiLCJlbWFpbCI6ImFiY2RAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjIwMzczODEsImV4cCI6MTY2MjAzNzY4MX0.mjVRx_7yJJ_XFNZRyGpCQ7upBc6jesjJp7aTIk-98U0

###
GET http://localhost:5491/project/delete/:abc
Content-Type: application/json


###
POST http://localhost:5491/project/complete
Content-Type: application/json

{
    "projectName":"abcd"
}

